export const headerLinks = [
  {
    label: "Trang chủ",
    route: "/",
  },
  {
    label: "Giới thiệu",
    route: "/aboutus",
  },
  {
    label: "Tin Tức",
    route: "/news",
  },
];

export enum Delimiter {
  Semicolon = ";",
  Enter = "Enter",
  Space = " ",
}

export enum FieldName {
  Title = "title",
  Slogan = "slogan",
  DisplayType = "displayType",
  RegisNum = "registrationNumber",
  Cate = "category",
  Formu = "formulation",
  Intro = "manual.intro",
  uHow = "manual.useHow",
  uWhen = "manual.useWhen",
  uAmount = "manual.useAmount",
  Note = "manual.note",
  ImageUrl = "imageUrl",
  Benefit = "benefit",
  Char = "characteristic",
  Price = "price",
  Mfg = "mfg",
  Exp = "exp",
  Quarantine = "manual.quarantine",
  SafeInstu = "manual.safetyInstruction",
  AfterUse = "manual.afterUse",
  FirstAid = "manual.firstAid",
  Manufacturer = "manufacturer",
  Packager = "packager",
  Register = "register",
  Distributer = "distributer",
  DisAt = "distributedAtCountry",
  Ingre = "ingredients",
}

export const translator = {
  title: "tên sản phẩm",
  slogan: "câu quảng bá",
  displayType: "cách trình bày sản phẩm",
  registrationNumber: "mã số đăng ký",
  image: "hình ảnh sản phẩm",
  imageUrl: "đường link hình ảnh",
  price: "giá sản phẩm",
  ingredient: "nguyên liệu",
  ingredients: "nguyên liệu",
  additive: "phụ gia",
  amount: "liều lượng",
  category: "chủng loại thuốc",
  formulation: "công thức thuốc",
  characteristic: "tính chất thuốc",
  benefit: "lợi ích của sản phẩm",
  manual: "hướng dẫn sử dụng",
  intro: "giới thiệu sản phẩm",
  useHow: "cách sử dụng sản phẩm",
  useWhen: "thời điểm phun thuốc",
  useAmount: "liều lượng sử dụng",
  crop: "cây trồng",
  pest: "dịch hại",
  note: "những lưu ý khi sử dụng sản phẩm",
  quarantine: "thời gian cách ly",
  safetyInstruction: "hướng dẫn an toàn chung",
  afterUse: "xử lý sau sử dụng",
  firstAid: "sơ cấp cứu",
  mfg: "ngày sản xuất",
  exp: "hạn sử dụng",
  manufacturer: "đơn vị sản xuất sản phẩm",
  register: "đơn vị đăng ký sản phẩm",
  packager: "đơn vị đóng gói sản phẩm",
  distributer: "đơn vị phân phối sản phẩm",
  distributedAtCountry: "phân phối tại các quốc gia",
};

export const productDefaultValues = {
  title: "",
  slogan: "",
  displayType: "1",
  registrationNumber: "",
  imageUrl: "",
  price: "",
  ingredients: [],
  category: "",
  formulation: "",
  characteristic: [
    "có thể có hại nếu nuốt phải thuốc",
    "có thể có hại nếu hít phải thuốc",
    "có thể có hại khi tiếp xúc với da",
  ],
  benefit: [],
  manual: {
    intro: "",
    useHow: "",
    useWhen: "",
    useAmount: [],
    note: "",
    quarantine: "",
    safetyInstruction:
      "Để xa tầm tay với của trẻ em. Đọc kỹ nhãn thuốc trước khi dùng. Không hút thuốc, ăn hoặc uống trong khi sử dụng sản phẩm này. Khi tiếp xúc hoặc chuẩn bị thuốc: tránh hít phải thuốc; tránh để thuốc tiếp xúc với miệng, da và mắt. Mang bảo hộ lao động phù hợp. Nếu bị dính thuốc: ngay lập tức cởi quần áo bị dính hoặc bị bắn nhiều thuốc; rửa kỹ phần bị dính thuốc bằng nhiều nước. Sau khi sử dụng: rửa chân tay và tắm rửa. Rửa sạch trang thiết bị bảo hộ lao động",
    afterUse:
      "Giữ kín trong bao gói gốc được dãn nhãn. KHÔNG sử dụng lại bao gói này vì bất kỳ mục đích nào khác. Để bao gói ở nơi an toàn, tránh xa thức ăn, trẻ em và động vật. Bỏ bao gois sau sử dụng đúng nơi quy định. Bao gói sau sử dụng phải được rửa 3 lần.",
    firstAid:
      "Thuốc dính vào mắt phải rửa bằng nước sạch ít nhất 15 phút. Nếu nuốt phải thuốc phải đưa ngay bệnh nhân tới bệnh viện gần nhất, kèm theo nhãn thuốc để bác sĩ điều trị theo triệu chứng.",
  },
  mfg: "xem trên bao bì",
  exp: "",
  manufacturer: "",
  register: "",
  packager: "",
  distributer: "",
  distributedAtCountry: [],
};
